### ISSUE TITLE
New feature of hash value

### ISSUE THREAD

**Issue by goodseller** [lavinjj/angularjs-gravatardirective#22]
Hi @lavinjj,

I add a feature to angularjs-gravatardirective, you can add hashed email string directly as an attribute or email. Would you like to hv a try and consider merge them? Thanks.

https://github.com/goodseller/angularjs-gravatardirective/

**Comment by goodseller** [comment]
@lavinjj  I have updated with tests. Please have a look. https://github.com/goodseller/angularjs-gravatardirective
Do I need to add a pull request also?

**Comment by lavinjj** [comment]
Yes, please send a pull request and I'll integrate it.
